apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ pluck .Values.environment .Values.aws.account | first }}:role/ssm-connector-role
  labels:
    app: ssm-connector-{{.Values.random}}
  name: ssm-connector-{{.Values.random}}
  namespace: ssm-connector
